import React from "@wordpress/element";

const CreatePayroll = () => {
    const tableData = [
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        {
            id: 1,
            employeeName: "John Doe",
            designation: "Manager",
            department: "Sales",
            basic: 5000,
            allowance: {
                pf: 1000,
                houseRent: 2000,
                medical: 500,
            },
            totalAllowance: 3500,
            deductions: {
                pf: 500,
                medical: 200,
                other: 100,
            },
            totalDeductions: 800,
            netPayable: 2700,
            nonTaxableAllowance: {
                tickets: 200,
                loan: 100,
                mobile: 50,
                food: 150,
                fuel: 100,
                festival: 300,
            },
            totalPayable: 2500,
        },
        // Add more data rows as needed
    ];

    return (
        <div className="payroll-table-container">
            <table className="payroll-table">
                <thead>
                <tr>
                    <th rowSpan={2}>Sl</th>
                    <th rowSpan={2} className="fixed-column">Employee Name</th>
                    <th rowSpan={2}>Designation</th>
                    <th rowSpan={2}>Department</th>
                    <th rowSpan={3}>Basic</th>
                    {/* Additional header columns */}
                    <th colSpan={3}>Allowance</th>
                    <th rowSpan={2}>Total Allowance</th>
                    <th colSpan={3}>Deductions</th>
                    <th rowSpan={2}>Total Deductions</th>
                    <th rowSpan={2}>Net Payable</th>
                    <th rowSpan={2}>Non-Taxable Allowance</th>
                    <th rowSpan={2}>Total Payable</th>
                </tr>
                <tr className="next-row">
                    <th>House Rent</th>
                    <th>Medical</th>
                    <th>P.F</th>
                    <th>Tax</th>
                    <th>P.F</th>
                    <th>Medical</th>
                </tr>
                </thead>
                <tbody>
                {tableData.map((data, index) => (
                    <tr key={data.id}>
                        <td>{index + 1}</td>
                        <td className="fixed-column">{data.employeeName}</td>
                        <td>{data.designation}</td>
                        <td>{data.department}</td>
                        <td>{data.basic}</td>
                        {/* Additional body columns */}
                        <td>{JSON.stringify(data.allowance)}</td>
                        <td>{data.totalAllowance}</td>
                        <td>{JSON.stringify(data.deductions)}</td>
                        <td>{data.totalDeductions}</td>
                        <td>{data.netPayable}</td>
                        <td>{JSON.stringify(data.nonTaxableAllowance)}</td>
                        <td>{data.totalPayable}</td>
                    </tr>
                ))}
                </tbody>
            </table>
        </div>
    );
};

export default CreatePayroll;
