import {CloseButton} from "./CloseButton";

type ModalProps = {
    setShowModal: React.Dispatch<React.SetStateAction<boolean>>;
    header?: React.ReactNode;
    children?: React.ReactNode;
};

export const Modal = ({ setShowModal, header, children }: ModalProps) => (
    <>
        <div className="justify-center items-start py-8 lg:pl-72 sm:pl-60 flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none">
            <div className="relative w-auto my-6 mx-auto max-w-6xl">
                <div className="border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none">
                    <div className="flex items-start justify-between p-5 border-b border-solid border-slate-200 rounded-t">
                        {header || (
                            <h3 className="text-3xl font-semibold">I know, I can do it!</h3>
                        )}
                        <CloseButton onClick={() => setShowModal(false)} />
                    </div>
                    <div className="relative px-14 py-4 flex-auto">
                        {children || (
                            <p className="my-4 text-gray-600 text-lg leading-relaxed">
                                <blockquote className="text-xl italic font-semibold text-gray-900 p-4 my-4 border-l-4 border-gray-300 bg-gray-50">
                                    I always felt like I could do anything. That’s
                                    the main thing people are controlled by! Thoughts
                                    - their perception of themselves! They're slowed
                                    down by their perception of themselves. If you're
                                    taught you can’t do anything, you won’t do anything.
                                    I was taught I could do everything.
                                </blockquote>
                                <div className="flex justify-between">
                                    <p>This text is generated by GitHub Copilot.</p>
                                    <p>
                                        This is shown, when there is no children to render!
                                    </p>
                                </div>

                            </p>
                            )}
                    </div>
                </div>
            </div>
        </div>
        <div className="opacity-25 fixed inset-0 z-40 bg-black"></div>
    </>
);
